### ISSUE TITLE
Code examples

### ISSUE THREAD

**Issue by eduardoHoefel** [lmendo/MATL#8]
Hello,

I'm sorry but couldn't find your email address so I'm asking this favor through an Issue.

I'm trying to learn your language but could not figure out how to create and add numbers to an array.

I've got this program:
`to?3*Q}2/]tq}x@
that prints the number of iteractions to run a collatz conjecture up to 1.
I'd like to modify it so it prints the whole set instead of its length.

**Comment by lmendo** [comment]
To print the whole set, the simplest way is to add another `t` so that each number gets stored in the stack:

`to?3*Q}2/]ttq]x

[Try it online!](https://tio.run/##y00syfn/P6Ek395YK7DWSD@2pKQwtuL/f0MDAA)

Note that the above doesn't concatenate the elements in an array, but leaves them as individual numbers on the stack. To concatenate you can use the functions `h` (concatenate horizontally, two inputs by default) and `v` (concatenate vertically, whole stack by default). See [example 1](https://tio.run/##y00syfn/P9pIwUTBLFbBUiHj/38A) and [example 2](https://tio.run/##y00syfn/P9pIwUTBLFbBUiHa1FrBPFah7P9/AA)

If you have a [PPCG account](https://codegolf.stackexchange.com/) you can visit the [MATL chatroom](https://chat.stackexchange.com/rooms/39466/matl-chatl) and ask any question there. Maybe that's easier than here, and other users can participate too.

**Comment by eduardoHoefel** [comment]
Thank you very much!
I didn't know about this chat tool. I'm going to use that next time.

Actually, I'm developing a code golf language myself as my undergraduate
thesis and prove that it's competitive and Turing complete.
So, I need to compare my programs with other languages.

I still need to get other examples in MATL but I'll try to code them by
myself :)

2018-05-29 8:23 GMT-03:00 Luis Mendo <notifications@github.com>:
