### ISSUE TITLE
Potential golfing oppurtunity

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [lmendo/MATL#9]
This could be an unrealistic way to shave bytes, but I thought I'd mention it just in case.

In [this answer](https://codegolf.stackexchange.com/a/170070/31957), I noticed an odd pattern:

```
&*XRXzXM
```

The final 3 functions were all modified by `X`. Could it be useful to have something like "enable implicit modifier"? I'll use `<M>_` to denote this, seeing as `X_`, `Y_`, and `Z_` are unused. This answer could become:

```
&*X_RzM
```

...saving 1 byte. It is very situational, but maybe common enough to warrant this shorthand. I want to do a bit of a corpus analysis to see if this would do anything useful, similar to [lynn's](https://github.com/DennisMitchell/jellylanguage/issues/69) for Jelly

**Comment by lmendo** [comment]
Thanks for the idea! However, as you say it seems to be very situational. Using [@Suever's analytics script](https://github.com/suever/matl-analytics), I've done a quick check of all 1640 MATL answers so far. There are:

 - one answer with three or more `X` functions in a row, besides the one you mention, which is not detected by the script, probably because the code is in a second part of the answer;
 - none with `Y`;
 - two with `Z`.

So it seems to be relatively rare. Besides, in two of those four cases the functions are not at the end of the code, so a closing modifier would be required, increasing the byte count.
